version: "3.8"
services:

  # GraphDB
  graphdb:
    image: ontotext/graphdb:10.6.1
    ports:
      - target: 7200
        published: 7200
        protocol: tcp

  # uservice
  uservice:
    image: dataplatform-shaper-uservice:latest
    ports:
      - target: 8093
        published: 8093
        protocol: tcp
    restart: always
    depends_on:
      - graphdb
    environment:
      GRAPHDB-HOST: graphdb
      GRAPHDB-CREATE-REPO: true
