version: "3.8"
services:

  # GraphDB
  graphdb:
    image: ontotext/graphdb:10.3.1
    network_mode: "host"

  # uservice
  uservice:
    image: dataplatform-shaper-uservice:latest
    network_mode: "host"
    restart: always
    depends_on:
      - graphdb
    environment:
      GRAPHDB-HOST: ${HOST_IP}
      GRAPHDB-CREATE-REPO: true

