openapi: 3.0.3
info:
  title: Ontology Manager
  description: 'This is the microservice responsible to manage user-defined types and instances'
  version: '__VERSION__'
servers:
  - #__URL__
tags:
  - name: OntologyManager
    description: All the ontology related operations
paths:
  /ontology/entity-type:
    post:
      tags:
        - OntologyManager
      summary: Create a user-defined type
      operationId: createType
      requestBody:
        description: An EntityType spec
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EntityType'
        required: true
      responses:
        200:
          description: If successful returns "OK"
          content:
            application/text:
              schema:
                type: string
        400:
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationError'
        500:
          description: System problem
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SystemError'
    get:
      tags:
        - OntologyManager
      summary: Get a user-defined type
      operationId: readType
      parameters:
        - in: query
          name: name
          required: true
          schema:
            type: string
            description: user-defined type name
      responses:
        200:
          description: If successful return an EntityType object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EntityType'
        400:
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationError'
        500:
          description: System problem
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SystemError'
  /ontology/entity-type/yaml:
    post:
      tags:
        - OntologyManager
      summary: Create a user-defined type
      operationId: createTypeByYaml
      requestBody:
        description: An YAML file containing an Entity Type spec
        required: true
        content:
          application/octet-stream:
            schema:
              type: string
              format: binary
      responses:
        200:
          description: If successful returns "OK"
          content:
            application/text:
              schema:
                type: string
        400:
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationError'
        500:
          description: System problem
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SystemError'
  /ontology/entity:
    post:
      tags:
        - OntologyManager
      summary: Create a user-defined type instance
      operationId: createEntity
      requestBody:
        description: An Entity spec
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Entity'
        required: true
      responses:
        200:
          description: If successful returns "OK"
          content:
            application/text:
              schema:
                type: string
        400:
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationError'
        500:
          description: System problem
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SystemError'
  /ontology/entity/{id}:
    get:
      tags:
        - OntologyManager
      summary: Get a user-defined type instance
      operationId: readEntity
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
            description: user-defined type instance id
      responses:
        200:
          description: If successful return an EntityType object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Entity'
        400:
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationError'
        500:
          description: System problem
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SystemError'
  /ontology/entity/yaml:
    post:
      tags:
        - OntologyManager
      summary: Create a user-defined type instance
      operationId: createEntityByYaml
      requestBody:
        description: An YAML file containing an Entity spec
        required: true
        content:
          application/octet-stream:
            schema:
              type: string
              format: binary
      responses:
        200:
          description: If successful returns "OK"
          content:
            application/text:
              schema:
                type: string
        400:
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationError'
        500:
          description: System problem
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SystemError'
  /ontology/entity/{id}/yaml:
    get:
      tags:
        - OntologyManager
      summary: Get a user-defined type instance as a YAML file
      operationId: readEntityAsYaml
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
            description: user-defined type instance id
      responses:
        200:
          description: If successful return an EntityType object
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
        400:
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationError'
        500:
          description: System problem
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SystemError'
components:
  schemas:
    Entity:
      required:
        - entityId
        - entityTypeName
        - values
      type: object
      properties:
        entityId:
          type: string
        entityTypeName:
          type: string
        values:
          $ref: '#/components/schemas/Values'
    EntityType:
      required:
        - name
        - schema
      type: object
      properties:
        name:
          type: string
        traits:
          type: array
          items:
            type: string
        schema:
          $ref: '#/components/schemas/Schema'
        fatherName:
          type: string
    Values:
      type: object
    Schema:
      type: array
      items:
        $ref: '#/components/schemas/AttributeType'
    AttributeType:
      type: object
      required:
        - name
        - typeName
      properties:
        name:
          type: string
        typeName:
          $ref: '#/components/schemas/AttributeTypeName'
        mode:
          $ref: '#/components/schemas/Mode'
        attributeTypes:
          type: array
          items:
            $ref: '#/components/schemas/AttributeType'
    AttributeTypeName:
      type: string
      enum:
        - String
        - Integer
        - Struct
    Mode:
      type: string
      enum:
        - Required
        - Repeated
        - Nullable
    ValidationError:
      required:
        - errors
      type: object
      properties:
        errors:
          type: array
          items:
            type: string
    SystemError:
      required:
        - error
      type: object
      properties:
        error:
          type: string
