object Versions {
   lazy val http4sVersion                    = "0.23.27"
   lazy val rdf4jVersion                     = "4.3.12"
   lazy val flywayVersion                    = "10.14.0"
   lazy val fly4sVersion                     = "1.0.0"
   lazy val doobieVersion                    = "1.0.0-RC4"
   lazy val postgresqlVersion                = "42.7.3"
   lazy val virtuosoJDBCVersion              = "3.123"
   lazy val virtuosoRDF4JVersion             = "1.17"
   lazy val dataToolsVersion                 = "1.3.2"
   lazy val typesafeConfig                   = "1.4.3"
   lazy val catsVersion                      = "2.12.0"
   lazy val catsEffectVersion                = "3.5.4"
   lazy val catEffectTestingVersion          = "1.5.0"
   lazy val catsEffectLoggingVersion         = "2.7.0"
   lazy val mulesVersion                     = "0.7.0"
   lazy val elApiVersion                     = "6.0.0"
   lazy val elImplVersion                    = "5.0.0"
   lazy val circeVersion                     = "0.14.7"
   lazy val circeYamlVersion                 = "1.15.0"
   lazy val calciteVersion                   = "1.37.0"
   lazy val scalaLogging                     = "3.9.5"
   lazy val logbackVersion                   = "1.5.6"
   lazy val scalatestVersion                 = "3.2.18"
   lazy val testContainersVersion            = "1.19.8"
 }
