object Versions {
   lazy val http4sVersion                    = "0.23.23"
   lazy val rdf4jVersion                     = "4.3.6"
   lazy val dataToolsVersion                 = "1.3.1"
   lazy val typesafeConfig                   = "1.4.2"
   lazy val catsVersion                      = "2.10.0"
   lazy val catsEffectVersion                = "3.5.1"
   lazy val catEffectTestingVersion          = "1.5.0"
   lazy val catsEffectLoggingVersion         = "2.6.0"
   lazy val circeVersion                     = "0.14.6"
   lazy val circeYamlVersion                 = "0.14.2"
   lazy val openapiValidatorVersion          = "2.37.0"
   lazy val scalaLogging                     = "3.9.5"
   lazy val logbackVersion                   = "1.4.11"
   lazy val scalatestVersion                 = "3.2.17"
   lazy val testContainersVersion            = "1.19.0"
   lazy val opentelemetryVersion             = "1.30.1"
   lazy val opentelemetryAnnotationsVersion  = "1.29.0"
 }
