name: Deploy scoverage-report to gh-pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install asdf
        uses: asdf-vm/actions/setup@v3
      - name: Install cue
        run: |
          asdf plugin add cue
          asdf install cue 0.9.2
          asdf global cue 0.9.2
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - name: Create scoverage-report
        run: |
          sbt clean
          sbt coverage test
          sbt coverageAggregate coverageReport
      - name: Make report available for deploy
        uses: actions/upload-artifact@v4
        with:
          name: scoverage-report
          path: ./target/scala-3.3.3/scoverage-report

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Get report from build job
        uses: actions/download-artifact@v4
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./scoverage-report
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
